/**
 * Minesweeper-api
 * This is a minesweeper-api description. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: her.ojeda2@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.hojeda.minesweeper.klient.api

import org.hojeda.minesweeper.klient.infrastructure.client.RestClient


class HealthApi(
    private val restClient: RestClient
) {

    /**
     * Health check
     * 
     * @return void
     */
    fun ping(): String = restClient.get("/ping").body

}
